USE [master]
GO
/****** Object:  Database [spotify]    Script Date: 17/12/2021 16:10:53 ******/
CREATE DATABASE [spotify]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'spotify', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\spotify.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'spotify_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\spotify_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [spotify] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [spotify].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [spotify] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [spotify] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [spotify] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [spotify] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [spotify] SET ARITHABORT OFF 
GO
ALTER DATABASE [spotify] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [spotify] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [spotify] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [spotify] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [spotify] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [spotify] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [spotify] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [spotify] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [spotify] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [spotify] SET  DISABLE_BROKER 
GO
ALTER DATABASE [spotify] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [spotify] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [spotify] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [spotify] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [spotify] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [spotify] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [spotify] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [spotify] SET RECOVERY FULL 
GO
ALTER DATABASE [spotify] SET  MULTI_USER 
GO
ALTER DATABASE [spotify] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [spotify] SET DB_CHAINING OFF 
GO
ALTER DATABASE [spotify] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [spotify] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [spotify] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'spotify', N'ON'
GO
ALTER DATABASE [spotify] SET QUERY_STORE = OFF
GO
USE [spotify]
GO
/****** Object:  Table [dbo].[Tracks]    Script Date: 17/12/2021 16:10:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tracks](
	[ISRC] [varchar](50) NOT NULL,
	[URI] [varchar](100) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[ArtistNames] [varchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [spotify] SET  READ_WRITE 
GO
